getwd()
install.packages("haven")
library(haven)
library(tidyverse)
data0203 <- read_dta("IDBR42FL.DTA")
view(data0203)
data.child0203 <- read_dta("IDKR42FL.DTA")
view(data.child0203)
install.packages("labelled")
library(labelled)
labelled::look_for(data,child0203,"region")
